databases:
  - name: filq_site
    databaseName: filq_site
    user: filq_site_user

services:
  - type: web
    name: FILQ-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filq_site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false